// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjmnmwyhdshliqtxlqvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbW5td3loZHNobGlxdHhscXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODY5NTYsImV4cCI6MjA3MDE2Mjk1Nn0.b-hSjRlwFQgG55_cXZTk7hub-5tKV08-3gyrMaSh-Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});